#!/bin/bash
# This `DEBIAN/postrm` script is run post-remove

if [ -f /etc/udev/rules.d/99-omodsim.rules ]; then
    rm -f /etc/udev/rules.d/99-omodsim.rules
    udevadm trigger || true
fi

update-mime-database /usr/share/mime || true
xdg-desktop-menu forceupdate || true
update-desktop-database -q /usr/share/applications || true
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
rm -f /usr/bin/omodsim2
