#!/bin/bash
# This `DEBIAN/postinst` script is run post-installation
set -e

if [ -f /etc/udev/rules.d/99-omodsim.rules ]; then
    rm -f /etc/udev/rules.d/99-omodsim.rules
fi

if [ ! -f /etc/udev/rules.d/99-omodscan.rules ]; then
    printf  "KERNEL==\"ttyS[0-9]*\", GROUP=\"dialout\", MODE=\"0666\"\n"  >> /etc/udev/rules.d/99-omodsim.rules
    printf  "KERNEL==\"ttyUSB[0-9]*\", GROUP=\"dialout\", MODE=\"0666\"\n"  >> /etc/udev/rules.d/99-omodsim.rules
fi

udevadm trigger

setcap 'cap_net_bind_service=+ep' /opt/OpenModSim2/bin/omodsim || true
ln -sf /opt/OpenModSim2/omodsim.sh /usr/bin/omodsim2

update-mime-database /usr/share/mime || true
xdg-desktop-menu forceupdate
update-desktop-database -q /usr/share/applications || true
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true

# Astra Linux Fly caches Start Menu icons and may not reload them after package installation.
if command -v fly-start-menu >/dev/null 2>&1; then
    killall fly-start-menu || true
fi
