#ifndef _PCH_H_
#define _PCH_H_

#include <QAbstractButton>
#include <QAbstractEventDispatcher>
#include <QAbstractItemModel>
#include <QAbstractItemView>
#include <QAbstractListModel>
#include <QAbstractTextDocumentLayout>
#include <QAction>
#include <QApplication>
#include <QBitArray>
#include <QByteArray>
#include <QClipboard>
#include <QComboBox>
#include <QCommandLineParser>
#include <QCompleter>
#include <QDataStream>
#include <QDateTime>
#include <QDebug>
#include <QDialog>
#include <QElapsedTimer>
#include <QEvent>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFontDatabase>
#include <QFrame>
#include <QHash>
#include <QHelpContentWidget>
#include <QHelpEngine>
#include <QHostAddress>
#include <QIcon>
#include <QInputDialog>
#include <QIntValidator>
#include <QJSEngine>
#include <QJSValue>
#include <QKeyEvent>
#include <QLabel>
#include <QLineEdit>
#include <QList>
#include <QListView>
#include <QListWidget>
#include <QListWidgetItem>
#include <QLocale>
#include <QLoggingCategory>
#include <QMainWindow>
#include <QMap>
#include <QMdiSubWindow>
#include <QMenu>
#include <QMessageBox>
#include <QMetaEnum>
#include <QMetaProperty>
#include <QMetaType>
#include <QMimeData>
#include <QModbusDataUnit>
#include <QModbusDevice>
#include <QModbusDeviceIdentification>
#include <QModbusPdu>
#include <QModbusReply>
#include <QModbusServer>
#include <QModbusTcpConnectionObserver>
#include <QMouseEvent>
#include <QNetworkInterface>
#include <QObject>
#include <QPageSetupDialog>
#include <QPainter>
#include <QPalette>
#include <QPlainTextEdit>
#include <QPrintDialog>
#include <QPrinter>
#include <QPrinterInfo>
#include <QPushButton>
#include <QQueue>
#include <QRandomGenerator>
#include <QRegularExpression>
#include <QRegularExpressionValidator>
#include <QScrollBar>
#include <QSerialPort>
#include <QSerialPortInfo>
#include <QSettings>
#include <QStatusBar>
#include <QString>
#include <QStringListModel>
#include <QStringView>
#include <QStyle>
#include <QStyleOptionViewItem>
#include <QStyledItemDelegate>
#include <QSyntaxHighlighter>
#include <QTableWidgetItem>
#include <QTcpServer>
#include <QTcpSocket>
#include <QTextBlock>
#include <QTextBrowser>
#include <QTextCharFormat>
#include <QTextCodec>
#include <QTextDocument>
#include <QTextStream>
#include <QThread>
#include <QTimer>
#include <QTranslator>
#include <QUrl>
#include <QValidator>
#include <QVariant>
#include <QVersionNumber>
#include <QWidget>
#include <QWidgetAction>
#include <QXmlStreamReader>
#include <QXmlStreamWriter>
#include <QtCore/qmath.h>
#include <QtEndian>
#include <QtGlobal>
#include <QtMath>
#include <QtWidgets>

#include <array>
#include <deque>
#include <limits>

#include <float.h>

#endif // _PCH_H_
