name: Build OpenModSim Installer (Windows x86, Qt5)

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Checkout branch'
        required: false
        default: dev
      tag:
        description: 'Checkout tag'
        required: false
      signing:
        description: 'Sign executable and installer'
        type: boolean
        default: false

permissions:
  contents: write

env:
  QT_VERSION: 5.15.2
  QT_ARCH: win32_msvc2019
  CMAKE_COMPILER: msvc2019
  CMAKE_GENERATOR: "Visual Studio 17 2022"
  CMAKE_ARCH: Win32
  ARCH: x86
  BUILD_TYPE: Release
  EXE_PACKAGE_PREFIX: qt5-omodsim2

  # SingPath variables
  PROJECT_SLUG: OpenModSim
  ORGANIZATION_ID: 6aeb3196-43e9-4b2c-83db-d1d90af47bc4
  ARTIFACT_CONF_SLUG: exe-zip

jobs:
  build-omodsim:
    name: Build OpenModSim installer version '${{ github.event.inputs.tag || github.event.inputs.branch || github.ref_name }}' with Qt5 on Windows x86
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.tag || github.event.inputs.branch || github.ref_name }}

      - name: Extract version from CMakeLists.txt
        run: |
          $versionMatch = Select-String -Path src\CMakeLists.txt -Pattern 'VERSION\s+([0-9]+\.[0-9]+\.[0-9]+)' | Select-Object -First 1
          if (-not $versionMatch) { exit 1 }

          $APP_VERSION = $versionMatch.Matches[0].Groups[1].Value
          $PRERELEASE_ENABLED = 'false'
          $PRERELEASE_SUFFIX = ''
          $TAG_NAME = '${{ github.event.inputs.tag }}'
          if ([string]::IsNullOrEmpty($TAG_NAME) -and '${{ github.ref_type }}' -eq 'tag') {
            $TAG_NAME = '${{ github.ref_name }}'
          }

          if ($TAG_NAME -match '(beta[0-9]+|b[0-9]+|rc[0-9]+)$') {
            $PRERELEASE_ENABLED = 'true'
            $PRERELEASE_SUFFIX = $Matches[1]
            $APP_VERSION = "$APP_VERSION-$PRERELEASE_SUFFIX"
          }

          "APP_VERSION=$APP_VERSION" >> $env:GITHUB_ENV
          "PRERELEASE_SUFFIX=$PRERELEASE_SUFFIX" >> $env:GITHUB_ENV
          "PRERELEASE_ENABLED=$PRERELEASE_ENABLED" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Convert version for dev branch
        if: ${{ github.ref_name == 'dev' || github.event.inputs.branch == 'dev' || startsWith(github.ref_name, 'release/') || startsWith(github.event.inputs.branch, 'release/') }}
        run: |
          for /f "tokens=1,2 delims=." %%a in ("%APP_VERSION%") do (
            echo APP_VERSION=%%a.%%b-dev>>%GITHUB_ENV%
          )
        shell: cmd

      - name: Select signing policy
        run: |
          set SIGNING_POLICY_SLUG=none
          if "${{ env.ORGANIZATION_ID }}"=="" (
            echo WARNING: ORGANIZATION_ID is not set or empty, skipping signing steps.
          ) else (
            if "${{ github.event_name }}"=="push" (
              if "${{ github.ref_type }}"=="tag" (
                for /f %%i in ('echo "${{ github.ref_name }}" ^| find /i "test"') do set TAG_HAS_TEST=1
                if not defined TAG_HAS_TEST (
                  set SIGNING_POLICY_SLUG=release-signing
                )
              )
            )
            if "${{ github.event_name }}"=="workflow_dispatch" (
              if "${{ github.event.inputs.signing }}"=="true" (
                if not "${{ github.event.inputs.tag }}"=="" (
                  echo "%{{ github.event.inputs.tag }}%" | find /i "test" >nul
                  if errorlevel 1 (
                    set SIGNING_POLICY_SLUG=release-signing
                  )
                ) else (
                  set SIGNING_POLICY_SLUG=test-signing
                )
              )
            )
          )
          echo SIGNING_POLICY_SLUG=%SIGNING_POLICY_SLUG%>>%GITHUB_ENV%
          echo Selected signing policy: %SIGNING_POLICY_SLUG%
        shell: cmd

      - name: Install Python (for aqtinstall)
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install aqtinstall
        run: |
          python -m pip install aqtinstall

      - name: Install Qt
        run: |
          python -m aqt install-qt windows desktop ${{ env.QT_VERSION }} ${{ env.QT_ARCH }} -O C:\Qt
        shell: cmd

      - name: Set BUILD_DIR
        run: |
          echo BUILD_DIR=build-omodsim-Qt_${{ env.QT_VERSION }}_${{ env.CMAKE_COMPILER }}bit-${{ env.BUILD_TYPE }}>>%GITHUB_ENV%
        shell: cmd

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
        with:
          vs-version: '16.11'

      - name: Get Visual Studio path
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" ^
           -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set VS_PATH=%%i
          echo VS_PATH=%VS_PATH%>>%GITHUB_ENV%
        shell: cmd

      - name: Configure CMake
        run: |
          cmake src -B ${{ env.BUILD_DIR }} -G "${{ env.CMAKE_GENERATOR }}" -A ${{ env.CMAKE_ARCH }} -T v142 -DCMAKE_PREFIX_PATH="C:/Qt/${{ env.QT_VERSION }}/${{ env.CMAKE_COMPILER }}" -DPROJECT_BETARELEASE=${{ env.PRERELEASE_SUFFIX }}
        shell: cmd

      - name: Build
        run: |
          cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }} --parallel
        shell: cmd

      - name: Copy docs
        run: xcopy %CD%\${{ env.BUILD_DIR }}\docs %CD%\${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\docs /E /I /Y
        shell: cmd

      - name: Copy demos
        run: xcopy %CD%\demos %CD%\${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\demos /E /I /Y
        shell: cmd

      - name: Upload Executable
        id: upload-exe
        uses: actions/upload-artifact@v7
        if: success()
        with:
          name: omodsim-${{ env.APP_VERSION }}_${{ env.ARCH }}.exe
          path: ${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\omodsim.exe

      - name: Signing Executable
        uses: signpath/github-action-submit-signing-request@v2
        if: success() && env.SIGNING_POLICY_SLUG != 'none'
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ env.ORGANIZATION_ID }}'
          project-slug: '${{ env.PROJECT_SLUG }}'
          signing-policy-slug: ${{ env.SIGNING_POLICY_SLUG }}
          artifact-configuration-slug: ${{ env.ARTIFACT_CONF_SLUG }}
          github-artifact-id: '${{steps.upload-exe.outputs.artifact-id}}'
          output-artifact-directory: ${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}
          wait-for-completion: true
          wait-for-completion-timeout-in-seconds: 3600

      - name: Upload signed Executable
        uses: actions/upload-artifact@v7
        if: success() && env.SIGNING_POLICY_SLUG != 'none'
        with:
          name: omodsim-${{ env.APP_VERSION }}_${{ env.ARCH }}-signed.exe
          path: ${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\omodsim.exe

      - name: Deploy Qt dependencies using windeployqt
        run: |
          call "${{ env.VS_PATH }}\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.29
          "C:\Qt\${{ env.QT_VERSION }}\${{ env.CMAKE_COMPILER }}\bin\windeployqt.exe" ^
            "%CD%\${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\omodsim.exe" ^
            --release ^
            --no-angle ^
            --no-quick ^
            --no-opengl-sw ^
            --no-system-d3d-compiler ^
            --plugindir "%CD%\${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\plugins"
        shell: cmd

      - name: Remove qml folder
        run: |
          IF EXIST "%CD%\${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\qml" (
            dir /a /b "%CD%\${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\qml" | findstr . >nul
            IF ERRORLEVEL 1 (
              rmdir "%CD%\${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\qml"
            ) ELSE (
              echo "qml folder is not empty - keeping it"
            )
          ) ELSE (
            echo "No qml folder found - nothing to remove"
          )
          exit /b 0
        shell: cmd

      - name: Install NSIS
        run: |
          choco install nsis -y
        shell: cmd

      - name: Build NSIS installer
        run: |
          "C:\Program Files (x86)\NSIS\makensis.exe" ^
           /DVERSION="${{ env.APP_VERSION }}" ^
           /DMIN_WINDOWS_VERSION=7 ^
           /DBUILD_PATH="%CD%\${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}" ^
           /DICON_FILE="%CD%\src\res\omodsim.ico" ^
           /DWELCOMEFINISHPAGE_BITMAP="%CD%\.github\win32\nsis3-omodsim.bmp" ^
           /DLICENSE_FILE="%CD%\src\res\license.txt" ^
           /DOUTPUT_FILE="%CD%\${{ env.EXE_PACKAGE_PREFIX }}-${{ env.APP_VERSION }}_${{ env.ARCH }}.exe" ^
           %CD%\.github\win32\installer-win32.nsi
        shell: cmd

      - name: Upload Installer
        id: upload-installer
        uses: actions/upload-artifact@v7
        if: success()
        with:
          name: ${{ env.EXE_PACKAGE_PREFIX }}-${{ env.APP_VERSION }}_${{ env.ARCH }}
          path: ${{ env.EXE_PACKAGE_PREFIX }}-${{ env.APP_VERSION }}_${{ env.ARCH }}.exe

      - name: Signing Installer
        uses: signpath/github-action-submit-signing-request@v2
        if: success() && env.SIGNING_POLICY_SLUG != 'none'
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ env.ORGANIZATION_ID }}'
          project-slug: '${{ env.PROJECT_SLUG }}'
          signing-policy-slug: ${{ env.SIGNING_POLICY_SLUG }}
          artifact-configuration-slug: ${{ env.ARTIFACT_CONF_SLUG }}
          github-artifact-id: '${{steps.upload-installer.outputs.artifact-id}}'
          output-artifact-directory: .
          wait-for-completion: true
          wait-for-completion-timeout-in-seconds: 3600

      - name: Upload signed Installer
        uses: actions/upload-artifact@v7
        if: success() && env.SIGNING_POLICY_SLUG != 'none'
        with:
          name: ${{ env.EXE_PACKAGE_PREFIX }}-${{ env.APP_VERSION }}_${{ env.ARCH }}-signed
          path: ${{ env.EXE_PACKAGE_PREFIX }}-${{ env.APP_VERSION }}_${{ env.ARCH }}.exe

      - name: Create or update GitHub Release and upload EXE
        if: success() && github.event_name == 'push' && github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          prerelease: ${{ env.PRERELEASE_ENABLED }}
          tag_name: ${{ github.ref_name }}
          name: Open ModSim ${{ env.APP_VERSION }}
          files: |
            ${{ env.EXE_PACKAGE_PREFIX }}-${{ env.APP_VERSION }}_${{ env.ARCH }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
