name: Build OpenModSim (Windows x64)

on:
  push:
    tags:
      - 'v*.*.*'
    branches: 
      - main
      - dev

env:
  QT_VERSION: 6.9.2
  QT_ARCH: win64_msvc2022_64
  CMAKE_COMPILER: msvc2022_64
  CMAKE_GENERATOR: "Visual Studio 17 2022"
  CMAKE_ARCH: x64
  BUILD_TYPE: Release

jobs:
  build-omodsim:
    name: Build OpenModSim version ${{ github.event.inputs.version || github.ref_name }}
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version || github.ref_name }}

      - name: Install Python (for aqtinstall)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install aqtinstall
        run: |
          python -m pip install aqtinstall

      - name: Install Qt
        run: |
          python -m aqt install-qt windows desktop ${{ env.QT_VERSION }} ${{ env.QT_ARCH }} -O C:\Qt -m qt5compat qtpdf qtserialport qtserialbus
        shell: cmd

      - name: Set BUILD_DIR
        run: |
          echo BUILD_DIR=build-omodsim-Qt_${{ env.QT_VERSION }}_${{ env.CMAKE_COMPILER }}bit-${{ env.BUILD_TYPE }}>>%GITHUB_ENV%
        shell: cmd

      - name: Configure CMake
        run: |
          cmake omodsim -B ${{ env.BUILD_DIR }} -G "${{ env.CMAKE_GENERATOR }}" -A ${{ env.CMAKE_ARCH }} -DCMAKE_PREFIX_PATH="C:/Qt/${{ env.QT_VERSION }}/${{ env.CMAKE_COMPILER }}"
        shell: cmd

      - name: Build
        run: |
          cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }} --parallel
        shell: cmd

      - name: Deploy Qt dependencies using windeployqt
        run: |
          "C:\Qt\${{ env.QT_VERSION }}\${{ env.CMAKE_COMPILER }}\bin\windeployqt.exe" ^
            "%CD%\${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}\omodsim.exe" ^
            --release ^
            --no-compiler-runtime ^
            --no-opengl-sw ^
            --add-plugin-types platforms,imageformats,styles,printsupport,serialport,serialbus
        shell: cmd

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: qt6-omodsim_${{ github.event.inputs.version || github.ref_name }}_x64
          path: |
            ./${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}/omodsim.exe
            ./${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}/*.dll
            ./${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}/platforms/
            ./${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}/docs/
            ./${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}/plugins/
            ./${{ env.BUILD_DIR }}\${{ env.BUILD_TYPE }}/translations/
            !**/*.pdb
