name: Build OpenModSim (Windows x64)

on:
  push:
    tags:
      - 'v*.*.*'
    branches: 
      - main
      - dev
      
#  workflow_dispatch:
#    inputs:
#      version:
#        description: "1.9.0"
#        required: true
#        default: "test-build"

env:
  QT_VERSION: "6.9.2"
  QT_ARCH: "win64_msvc2022_64"
  CMAKE_COMPILER: "msvc2022_64"
  CMAKE_GENERATOR: "Visual Studio 17 2022"
  CMAKE_ARCH: "x64"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version || github.ref_name }}

      - name: Install Python (for aqtinstall)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install aqtinstall
        run: |
          python -m pip install aqtinstall

      - name: Install Qt
        run: |
          python -m aqt install-qt windows desktop ${{ env.QT_VERSION }} ${{ env.QT_ARCH }} -O C:\Qt -m qt5compat qtpdf qtserialport qtserialbus
        shell: cmd

      - name: Configure CMake
        run: |
          cmake -B build -G ${{ env.CMAKE_GENERATOR }} -A ${{ env.CMAKE_ARCH }} -DCMAKE_PREFIX_PATH="C:/Qt/${{ env.QT_VERSION }}/${{ env.CMAKE_COMPILER }}"
        shell: cmd

      - name: Build
        run: |
          cmake --build build --config Release --parallel
        shell: cmd

      - name: Deploy Qt dependencies using windeployqt
        run: |
          "C:\Qt\${{ env.QT_VERSION }}\${{ env.CMAKE_COMPILER }}\bin\windeployqt.exe" build\omodsim.exe --release
        shell: cmd

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: qt6-omodsim_${{ github.event.inputs.version || github.ref_name }}_amd64
          path: |
            ./build/omodsim.exe
            ./build/*.dll
            ./build/platforms/
            ./build/docs/
            ./build/plugins/
            ./build/translations/
            !**/*.pdb
